framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session:
        # Default session settings here
        # Uncomment and configure as needed
        # handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"

    # Uncomment if using ESI or fragments
    # esi: true
    # fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
